# Generated by Django 3.1.3 on 2020-12-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201206_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field=60, upload_to='MEDIA_COMPANY_IMAGE_DIR', width_field=100),
        ),
    ]
