# Generated by Django 3.1.3 on 2020-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20201206_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialty',
            name='width_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='MEDIA_SPECIALITY_IMAGE_DIR', width_field='width_field'),
        ),
    ]
