# Generated by Django 3.1.3 on 2020-12-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20201212_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, height_field='height_field', upload_to='MEDIA_COMPANY_IMAGE_DIR', width_field='width_field'),
        ),
    ]
